language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get build-dep python-pygame
install:
  - pip install 'Pygame == 1.9.1release' --allow-external Pygame --allow-unverified Pygame
script: py.test test.py
